macro(subdirlist result search_dir)
  file(GLOB children RELATIVE ${search_dir} ${search_dir}/*)
  set(dirlist "")
  foreach(child ${search_dir})
    if(IS_DIRECTORY ${search_dir}/${child})
      list(APPEND dirlist ${child})
    endif()
  endforeach()
  set(${result} ${dirlist})
endmacro()
